// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    // Placeholder parseable para comandos que NO conectan a la DB (ej. `prisma generate`
    // en el build de Coolify, donde DATABASE_URL es runtime-only). `migrate deploy` y el
    // runtime usan siempre la DATABASE_URL real inyectada por el entorno.
    url: process.env.DATABASE_URL ?? 'postgresql://build:build@localhost:5432/build',
  },
});
