import { GiftCardBrand } from "@/generated/prisma/client";

export const BRANDS: { id: GiftCardBrand; name: string; icon: string }[] = [
  { id: "AMAZON", name: "Amazon", icon: "🛒" },
  { id: "EBAY", name: "eBay", icon: "🏪" },
  { id: "WALMART", name: "Walmart", icon: "🏬" },
  { id: "TARGET", name: "Target", icon: "🎯" },
  { id: "BEST_BUY", name: "Best Buy", icon: "📱" },
  { id: "HOME_DEPOT", name: "Home Depot", icon: "🏠" },
  { id: "LOWES", name: "Lowe's", icon: "🛠️" },
  { id: "MACY_S", name: "Macy's", icon: "🛍️" },
  { id: "KOHLS", name: "Kohl's", icon: "👕" },
  { id: "STEAM", name: "Steam", icon: "🎮" },
  { id: "PLAYSTATION_NETWORK", name: "PlayStation", icon: "🎮" },
  { id: "XBOX", name: "Xbox", icon: "🎮" },
  { id: "NINTENDO_ESHOP", name: "Nintendo eShop", icon: "🎮" },
  { id: "ROBLOX", name: "Roblox", icon: "🧱" },
  { id: "RAZER_GOLD", name: "Razer Gold", icon: "🐍" },
  { id: "APPLE_ITUNES", name: "Apple/iTunes", icon: "🍎" },
  { id: "GOOGL_PLAY", name: "Google Play", icon: "🎮" },
  { id: "NETFLIX", name: "Netflix", icon: "📺" },
  { id: "HULU", name: "Hulu", icon: "📺" },
  { id: "SPOTIFY", name: "Spotify", icon: "🎵" },
  { id: "STARBUCKS", name: "Starbucks", icon: "☕" },
  { id: "CHIPOTLE", name: "Chipotle", icon: "🌯" },
  { id: "DOMINOS", name: "Domino's", icon: "🍕" },
  { id: "UBER_EATS", name: "Uber Eats", icon: "🍔" },
  { id: "DOORDASH", name: "DoorDash", icon: "🚗" },
  { id: "CHEESECAKE_FACTORY", name: "Cheesecake Factory", icon: "🍰" },
  { id: "NIKE", name: "Nike", icon: "👟" },
  { id: "ADIDAS", name: "Adidas", icon: "👟" },
  { id: "SEPHORA", name: "Sephora", icon: "💄" },
  { id: "VANILLA_VISA", name: "Vanilla Visa", icon: "💳" },
];

export const COUNTRIES = [
  { id: "US", name: "United States", code: "USD" },
  { id: "CA", name: "Canada", code: "CAD" },
  { id: "UK", name: "United Kingdom", code: "GBP" },
  { id: "AU", name: "Australia", code: "AUD" },
  { id: "DE", name: "Germany", code: "EUR" },
  { id: "FR", name: "France", code: "EUR" },
  { id: "JP", name: "Japan", code: "JPY" },
  { id: "BR", name: "Brazil", code: "BRL" },
  { id: "MX", name: "Mexico", code: "MXN" },
];
